version: "3.7"
services:
  db:
    image: postgres:latest # pin the image version if you want
    restart: always
    environment:
      # POSTGRES_PASSWORD: REAPLCEME # user is `postgres`, this is the admin user
      POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD # use a docker secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10

# TODO: walg image and service, mount the volume in the same place

volumes:
  pgdata: # we're using a docker volume here
